name: dice_roller
description: A casual, interactive, single user, dice rolling game.
publish_to: 'none' # Prevent accidental publishing to pub.dev.
version: 0.0.1+1

environment:
  sdk: ^3.3.0

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  go_router: ^13.2.4
  provider: ^6.0.2
  shared_preferences: ^2.0.13

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.1.1
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/dices/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
