name: dice_roller
description: A casual, interactive, single user, dice rolling game.

version: 0.0.1+1

environment:
  sdk: ^3.11.0

dependencies:
  audioplayers: ^6.5.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13

dev_dependencies:
  build_runner: ^2.3.3
  extra_lints:
    git:
      url: https://github.com/mitulvaghamshi/extra_lints.git
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.0.0
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/clips/start.mp3
    - assets/clips/stop.mp3
    - assets/dices/dice_0.webp
    - assets/dices/dice_1.webp
    - assets/dices/dice_2.webp
    - assets/dices/dice_3.webp
    - assets/dices/dice_4.webp
    - assets/dices/dice_5.webp
    - assets/dices/dice_6.webp
    - assets/imgs/back.webp
    - assets/imgs/bar.webp
    - assets/imgs/box.webp
    - assets/imgs/cross.webp
    - assets/imgs/settings.webp
    - assets/imgs/2x/back.webp
    - assets/imgs/2x/bar.webp
    - assets/imgs/2x/box.webp
    - assets/imgs/2x/cross.webp
    - assets/imgs/2x/settings.webp
    - assets/imgs/3x/back.webp
    - assets/imgs/3x/bar.webp
    - assets/imgs/3x/box.webp
    - assets/imgs/3x/cross.webp
    - assets/imgs/3x/settings.webp
    - assets/imgs/3.5x/back.webp
    - assets/imgs/3.5x/bar.webp
    - assets/imgs/3.5x/box.webp
    - assets/imgs/3.5x/settings.webp

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
